# Welcome to Serverless!
#

service: example # NOTE: update this with your service name

plugins:
  - mfa-serverless-plugin

provider:
  name: aws
  runtime: nodejs8.10


functions:
  hello:
    handler: handler.hello

